name: Run unnittest automatically with PR on main and Push commit
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  unit-test-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: cd 3.\ Midterm/PhamVanToi 
    - run: sudo apt install python3-virtualenv
    - run: virtualenv venv && source venv/bin/activate
    - run: pip install unittest2 requests ansible
    - run: sudo apt-get update
    - run: ansible-playbook -i inventory.yml setup.yml
    - run: python3 ./roles/web/files/unit_test.py