name: Run unnittest automatically with PR on main and Push commit
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  unit-test-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: sudo apt-get update
    - run: sudo apt install apt-transport-https ca-certificates curl software-properties-common
    - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - run: sudo apt install docker-ce
    - run: sudo docker --version

        


    # - run: sudo apt install python3-virtualenv
    # - run: virtualenv venv && source venv/bin/activate
    # - run: pip install unittest2 requests ansible
    # - run: ansible --version

    # - run: ls
    # - run: python3 ./roles/web/files/unit_test.py