name: Run unnittest automatically with PR on main and Push commit
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: pip install unittest2 requests
    - run: python3 3.\ Midterm/PhamVanToi/roles/web/files/unit_test.py