name: Run unnittest automatically with PR on main and Push commit
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  unit-test-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: sudo apt-get update
    - run: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - run: sudo docker --version
    

        


    # - run: sudo apt install python3-virtualenv
    # - run: virtualenv venv && source venv/bin/activate
    # - run: pip install unittest2 requests ansible
    # - run: ansible --version

    # - run: ls
    # - run: python3 ./roles/web/files/unit_test.py